import '../css/styles.css';
import Tabs from './components/Tabs.js';
import Dropdown from './components/Dropdown.js';
import ModalManager from './components/Modal.js';
import Toast from './components/Toast.js';
import FormFactory from './components/FormFactory.js';
import ToggleDisplay from './behaviors/ToggleDisplay.js';
import CustomSportField from './behaviors/CustomSportField.js';
import CopyToClipboard from './behaviors/CopyToClipboard.js';
import DeleteAccount from './behaviors/DeleteAccount.js';
import DeleteGroup from './behaviors/DeleteGroup.js';
import DeleteEvent from './behaviors/DeleteEvent.js';
import EventVisibilitySwitcher from './behaviors/EventVisibilitySwitcher.js';
import LogoutAccount from './behaviors/LogoutAccount.js';
import RemoveGroupMember from './behaviors/RemoveGroupMember.js';
import RemoveEventParticipant from './behaviors/RemoveEventParticipant.js';
import RemoveEventComment from './behaviors/RemoveEventComment.js';
import PublicEventsLoader from './behaviors/PublicEventsLoader.js';

new Tabs();
new Dropdown();
new Toast();
new ToggleDisplay();
new CustomSportField();
new EventVisibilitySwitcher();
new CopyToClipboard();
new DeleteAccount();
new DeleteGroup();
new DeleteEvent();
new RemoveGroupMember();
new RemoveEventParticipant();
new RemoveEventComment();
new PublicEventsLoader();
new LogoutAccount();
new ModalManager();

FormFactory.createAll();
